GET http://localhost:3000/

###

GET http://localhost:3000/users

###

POST http://localhost:3000/users
content-type: application/json

{
  "email": "sample2",
  "nivel_acesso": "Wed, 21 Oct 2015 18:27:50 GMT",
  "senha": "sample"
}

###

PUT http://localhost:3000/users/2
content-type: application/json

{
  "email": "testee5",
  "nivel_acesso": "Wed, 21 Oct 2015 18:27:50 GMT",
  "senha": "sample"
}

###

DELETE http://localhost:3000/users/2

###
